excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://sylvain.artois.me
title: Sylvain Artois tech blog
tagline: Talking with computer
description: Weekly account about my techy days  as a software engineer at Etsy France. Mainly, Ux and Javascript, beautifull webdesign, intelligent web and text taming.
paginate: 10
