excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://sylvain.artois.me
title: Sylvain Artois, tech blog
tagline: From User to Computer
description: Weekly account about my techy days  as a fullstack software engineer at Etsy France - AlittleMarket. Mainly, Ux and Javascript, beautifull webdesign, intelligent web and text taming.
paginate: 5
